### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ItamarShDev** [nickjmiller/pytest-fixtures#15]
- Issue Type: `Performance`
- Extension Name: `pytest-fixtures`
- Extension Version: `0.2.2`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/ITAMAR~1/AppData/Local/Temp/nickmillerdev.pytest-fixtures-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nickjmiller** [comment]
Hi can you upload that linked file so I can take a look?

**Comment by ItamarShDev** [comment]
Sure. Once I'll get home. Thanks!

**Comment by ItamarShDev** [comment]
[nickmillerdev.pytest-fixtures-unresponsive.cpuprofile.txt](https://github.com/nickjmiller/pytest-fixtures/files/8921503/nickmillerdev.pytest-fixtures-unresponsive.cpuprofile.txt)

**Comment by ItamarShDev** [comment]
I think #19 can help here

**Comment by nickjmiller** [comment]
I'll close this now that your changes have been pushed
