### ISSUE TITLE
addition pytest arguments when discover fixtures

### ISSUE THREAD

**Issue by thu2004** [nickjmiller/pytest-fixtures#24]
Some time we need to add extra arguments when run "pytest --fixture" to discover fixtures from other pytest plugins. For example we have a pip packet called abcfw, we use "-p abcfw.pytest.common.bootstrap" to discover all fixtures inside the abcfw.

can you add such support such as ?

The solution is in the .vscode/settings.json we need to add the extra arguments and the plugin uses this args if exist.
{
    "pytest-fixtures.extra_arguments": [
        "-p",
        "cspfw.pytest.common.bootstrap",
    ]
}

**Comment by thu2004** [comment]
@nickjmiller is this project abandon ?

**Comment by nickjmiller** [comment]
No sorry, I haven't been able to dedicate as much time to this but this change looks good. One thing is the new command should be declared in the package.json but I can add that when I bump the version which I can do tomorrow.

**Comment by thu2004** [comment]
Thank you @nickjmiller . Please bump the version if not yet done.
