### ISSUE TITLE
Go-to-definition does not work for fixtures in test cases with big names 

### ISSUE THREAD

**Issue by ilolis** [nickjmiller/pytest-fixtures#31]
**Describe the bug**
If a test case:
1. has a name larger than 64 characters
2. **and** its arguments are in separate lines 

the go-to-definition will only work for the first fixture. 

**To Reproduce**
1. Copy the code that exists in the bottom of this Issue
2. Go to the test case with name `test_____________in_this_test_case_the_fixtures_are_in_seperate_lines___only_the_go_to_definition_of_the_first_fixture_works_____`
5. Try to go-to-definition of the `dummy_fixture_return_2`
7. Assert that go-to-definition does not work

**Expected behavior**
The go-to-definition should work for both of the fixtures. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: WSL2 on Windows 10 
 - Version Python 3.9, Ubuntu 20.04.04 LTS, Windows 10

**Please paste the output of `pytest --fixtures` for the affected file**
```
------- fixtures defined from tests.test_main -------
dummy_fixture_return_1 -- tests/test_main.py:5
    no docstring available

dummy_fixture_return_2 -- tests/test_main.py:9
    no docstring available

```

**You can find the command used by navigating to Output > pytest-fixtures, it should log out `Running command  /.../pytest --color no --fixtures -v /.../file.py in directory /.../Directory`. You can remove partial paths.**
When I click on the fixture `dummy_fixture_return_2` **nothing** is logged. 

**Attached Code:**

```
import pytest 

# Fixture definitions 
@pytest.fixture
def dummy_fixture_return_1():
    return 1

@pytest.fixture
def dummy_fixture_return_2():
    return 2

# simple function 
def plus(a,b):
    return a + b


# In test cases with a big name *and* with the *fixtures in the same line*, the go to definition works
# e.g.
def test_____________in_this_test_case_the_go_to_definition_works_for_both_of_the_fixtures_____(dummy_fixture_return_1,dummy_fixture_return_2):
    assert plus(dummy_fixture_return_1,dummy_fixture_return_2) == 3

# In test cases with a big name *and* with the fixtures in *seperate* lines, the go to definition works only for the first fixture
def test_____________in_this_test_case_the_fixtures_are_in_seperate_lines___only_the_go_to_definition_of_the_first_fixture_works_____(
    dummy_fixture_return_1,   # Go to definition for this fixture works. 
    dummy_fixture_return_2    # Go to definition for this fixture *does not* work
    ):
    assert plus(dummy_fixture_return_1,dummy_fixture_return_2) == 3
```

**Comment by nickjmiller** [comment]
Thanks for bringing this up, it should be fixed in v0.2.6
