### ISSUE TITLE
In a multi-folder project, pytest-fixtures runs pytest with the first folder as CWD, not the folder where the tests are

### ISSUE THREAD

**Issue by tazle** [nickjmiller/pytest-fixtures#37]
In a multi-folder project, pytest-fixtures runs pytest with the first folder as CWD, not the folder under which the current file resides.

**Expected behavior**
Expected pytest-fixtures to run with the folder where the file resides as the CWD.

**Logs**
```
[05/02/2023 - 13:46:13] Active file changed; Loading fixtures for /Users/tuure/work/repo/server/tests/web_api/a_route.py
[05/02/2023 - 13:46:13] Running command /Users/tuure/work/repo/server/bin/run-pytest-in-compose.sh -m pytest --color no --fixtures -v /Users/tuure/work/repo/server/tests/web_api/a_route.py in directory /Users/tuure/work/repo/frontend
```

Note that the command gets run in directory */Users/tuure/work/repo/frontend*, not */Users/tuure/work/repo/server*.

After changing the `run-pytest-in-compose.sh` so that it switches to /Users/tuure/work/repo/server before running `docker-compose`, I get the fixture suggestions in test function parameter list.

**Desktop (please complete the following information):**
 - OS: Mac OS

**Comment by nickjmiller** [comment]
Yeah this was changed when adding a new feature a while ago, I don't remember the motivation. I can make a change to respect the file's directory, but I may put it behind a settings flag in case of regressions.

**Comment by tazle** [comment]
Our current workaround is to carefully order the directories in the workspace. Not dependingnon the order would definitely be useful.

**Comment by nickjmiller** [comment]
I've added a new setting in 0.2.9: `pytest-fixtures.useFileWorkspaceFolder`. Enable it and let me know if there are any issues. It should respect the workspace for each file rather than default to the working directory, but there may be unintended consequences in fixture parsing.

**Comment by tazle** [comment]
Tested the setting today. It appears to be working as expected. Thank you!
