### ISSUE TITLE
Doesn't run --fixture command

### ISSUE THREAD

**Issue by VitariPro** [nickjmiller/pytest-fixtures#38]
Hello,

I've installed pytest-fixtures to MS VS Code but it doesn't work.
Looks like it doesn't run the shell command.

pytest-fixtures output is:
`[2/14/2023 - 2:00:16 PM] Called provideCompletionItems: /opt/web/by_seq_tests.py, position: {"line":5,"character":56
[2/14/2023 - 2:00:16 PM] GetSuggestions: /opt/web/by_seq_tests.py
[2/14/2023 - 2:00:17 PM] Called provideDefinition: /opt/web/by_seq_tests.py, position: {"line":5,"character":49}`

I've try to specify absolute path python.testing.pytestPath and set python.testing.pytestEnable: true in workspace and user settings but have no effect.

Log(Extension Host):
`2023-02-16 16:21:09.316 [error] TypeError: Cannot read properties of undefined (reading 'find')
	at e.PytestFixtureProvider.getFixtures (/home/ololo/.vscode/extensions/nickmillerdev.pytest-fixtures-0.2.8/dist/extension.js:1:13455)
	at /home/ololo/.vscode/extensions/nickmillerdev.pytest-fixtures-0.2.8/dist/extension.js:1:13329`

**Comment by nickjmiller** [comment]
To confirm, you are not seeing something like this in the output? https://github.com/nickjmiller/pytest-fixtures/blob/56ff67545d5207e578bfcfa725c239daa45f8a89/src/fixture.ts#L49

Can you let me know your OS, python version, pytest version?
