### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by paraggit** [nickjmiller/pytest-fixtures#42]
- Issue Type: `Performance`
- Extension Name: `pytest-fixtures`
- Extension Version: `0.3.0`
- OS Version: `Darwin x64 22.5.0`
- VS Code version: `1.79.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/x8/sslwfk1d3kx9w93bgcyqpc_00000gn/T/nickmillerdev.pytest-fixtures-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nickjmiller** [comment]
This is a known issue, I will clarify in the readme.
