### ISSUE TITLE
Pytest extra arguments option winds up duplicating the base arguments

### ISSUE THREAD

**Issue by jxramos** [nickjmiller/pytest-fixtures#45]
**Describe the bug**
A bug was introduced in commit 97d00b0c942ef47bf03b6df47b8494c9c91a3608 that duplicates args.

**To Reproduce**
Navigate to some python source and look at the output tab dialed in to `pytest-fixtures` and look for the Running command trace

`Running command <selected_python_interpreter> -m pytest  --color no --fixtures -v <my_test_module.py>
--color no --fixtures -v <my_test_module.py>`

**Expected behavior**
Only one base argument set should be present

**Comment by nickjmiller** [comment]
Thanks for catching that, fixed in 0.3.1
