### ISSUE TITLE
Fixtures don't appear for autocompletion if function parameters span multiple lines

### ISSUE THREAD

**Issue by dtczest** [nickjmiller/pytest-fixtures#7]
```
def test_post_score_v1_batch_generates_archives_error_archives(enable_archiving_file_system, client_v5_ens_pip,
                                                               v1_endpoint, archive_dir,
                                                               lc_batch_payload_json_v1):
```

If I have a function definition like this, only the first line of the parameters will autocomplete fixtures. If I try to add a new fixture after 'lc_batch_payload_json_v1', no autocompletion pops up.

I think this is due to this code in suggestionProvider.ts:
```
            if (
                lineTextBeforePosition.includes("(") &&
                !lineTextBeforePosition.includes(")")
            ) {
```

AND due to how lineCanUseFixtureSuggestions works.

Also, Go To Definition isn't working for fixtures that aren't in the first line of function parameters. I believe this is because of how lineCanUseFixtureSuggestions works also.

**Comment by nickjmiller** [comment]
Yes this is definitely an issue, the current detection method is very naive and there are several issues with it. I will try to come up with a more robust method to detect if the extension can provide suggestions.

**Comment by dtczest** [comment]
Can confirm this is working now, thanks!
